export const technologies = [
  ['React', 'Front-end', 'Biblioteca para criação de interfaces baseadas em componentes.'],
  ['Angular', 'Front-end', 'Framework para aplicações web completas e estruturadas.'],
  ['Vue.js', 'Front-end', 'Framework progressivo para construção de interfaces.'],
  ['Vite', 'Build', 'Ferramenta rápida para desenvolvimento e build de aplicações web.'],
  ['Node.js', 'Back-end', 'Runtime JavaScript para execução fora do navegador.'],
  ['Express', 'Back-end', 'Framework minimalista para APIs e aplicações Node.js.'],
  ['NestJS', 'Back-end', 'Framework Node.js com arquitetura modular.'],
  ['Spring Boot', 'Back-end', 'Framework Java para aplicações e APIs.'],
  ['ASP.NET Core', 'Back-end', 'Framework .NET para aplicações web e APIs.'],
  ['Django', 'Back-end', 'Framework web Python com abordagem batteries-included.'],
  ['FastAPI', 'Back-end', 'Framework Python moderno para construção de APIs.'],
  ['PostgreSQL', 'Banco de Dados', 'Banco de dados relacional open source.'],
  ['MySQL', 'Banco de Dados', 'Sistema gerenciador de banco de dados relacional.'],
  ['MongoDB', 'Banco de Dados', 'Banco orientado a documentos.'],
  ['Redis', 'Banco de Dados', 'Armazenamento em memória usado para cache e filas.'],
  ['Docker', 'DevOps', 'Plataforma para empacotar aplicações em containers.'],
  ['Kubernetes', 'DevOps', 'Orquestrador de containers para ambientes distribuídos.'],
  ['Git', 'DevOps', 'Sistema distribuído de controle de versão.'],
  ['GitHub Actions', 'CI/CD', 'Automação de workflows diretamente no GitHub.'],
  ['GitLab CI/CD', 'CI/CD', 'Ferramenta de integração e entrega contínuas do GitLab.'],
  ['Jenkins', 'CI/CD', 'Servidor de automação para pipelines de software.'],
  ['SonarQube', 'Qualidade', 'Plataforma para inspeção contínua da qualidade do código.'],
  ['ESLint', 'Qualidade', 'Ferramenta de análise de código JavaScript e TypeScript.'],
  ['Vitest', 'Testes', 'Framework de testes integrado ao ecossistema Vite.'],
  ['Jest', 'Testes', 'Framework de testes para JavaScript.'],
  ['Playwright', 'Testes', 'Framework para testes end-to-end em navegadores.'],
  ['Cypress', 'Testes', 'Ferramenta para testes end-to-end de aplicações web.'],
  ['Nginx', 'Infraestrutura', 'Servidor web e reverse proxy de alto desempenho.'],
  ['Terraform', 'Infraestrutura', 'Ferramenta de infraestrutura como código.'],
  ['Grafana', 'Observabilidade', 'Plataforma para dashboards, métricas e observabilidade.'],
].map(([name, category, description], index) => ({ id: index + 1, name, category, description }));
